services:
  name: api
  image: lucky059-swiftdeploy:latest
  port: 4000
  mode: stable
  version: "1.0.0"
  restart_policy: always

nginx:
  image: nginx:latest
  port: 9090
  proxy_timeout: 30

network:
  name: swiftdeploy-net
  driver_type: bridge

volumes:
  logs: app-logs