services:
  name: api
  image: lucky-swiftdeploy-stage4b:latest
  port: 3000
  mode: canary
  version: 1.0.0
  restart_policy: always
nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30
network:
  name: swiftdeploy-net
  driver_type: bridge
volumes:
  logs: app-logs
